# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production: 
  encoding: unicode
  adapter: postgresql
  username: bszpqzlfcr
  port: 5432
  host: ec2-50-17-213-61.compute-1.amazonaws.com
  database: bszpqzlfcr
  password: c4PfrlpI2XKbeUYUkzED
